import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const bridge = readFileSync(new URL('../components/SlideSyncBridge.vue', import.meta.url), 'utf8')
const sync = readFileSync(new URL('../composables/useSlideLiveSync.ts', import.meta.url), 'utf8')
const drawings = readFileSync(new URL('../utils/drawings.ts', import.meta.url), 'utf8')
const addonLayer = readFileSync(new URL('../global-top.vue', import.meta.url), 'utf8')
const themeLayer = readFileSync(new URL('../../slidev-theme-tulip-lab/global-top.vue', import.meta.url), 'utf8')

test('addon mounts the reviewed sync bridge without coupling it to the theme', () => {
  assert.match(addonLayer, /import SlideSyncBridge/)
  assert.match(addonLayer, /<SlideSyncBridge\s*\/>/)
  assert.doesNotMatch(themeLayer, /SlideSyncBridge/)
  assert.match(themeLayer, /useDeckNavigation/)
})

test('sync bridge keeps presenter authoritative and audience read-only', () => {
  assert.match(sync, /nav\.isPresenter/)
  assert.match(sync, /type: 'presenter_hello'/)
  assert.match(sync, /type: 'page'/)
  assert.match(sync, /page: nav\.currentPage\.value/)
  assert.match(sync, /clicks: nav\.clicks\.value/)
  assert.match(sync, /role\.value === 'audience'/)
  assert.match(sync, /nav\.clicks/)
  assert.match(sync, /nav\.go\(page, clicks\)/)
  assert.match(sync, /lockShortcuts/)
  assert.match(sync, /disableBuiltinSync/)
  assert.match(bridge, /slide-sync-audience/)
  assert.match(sync, /stopImmediatePropagation/)
  assert.match(bridge, /#slide-container > :not\(#slide-content\)/)
  assert.match(sync, /audienceConnections/)
  assert.match(sync, /type === 'presence'|\['state', 'presence'\]/)
  assert.match(sync, /'viewer' : 'viewers'/)
  assert.match(sync, /\$\{noun\} online/)
  assert.match(sync, /data\.type === 'ended'/)
  assert.match(sync, /location\.reload\(\)/)
  assert.doesNotMatch(sync, /localStorage|sessionStorage/)
})

test('live drawings and presenter fullscreen use the reviewed secure path', () => {
  assert.match(sync, /PROTOCOL_VERSION = 3/)
  assert.match(sync, /type: 'drawing'/)
  assert.match(sync, /onDrawingUpdate/)
  assert.match(sync, /committed/)
  assert.match(sync, /tulipPresenter/)
  assert.match(sync, /presenter-sync/)
  assert.match(sync, /nav\.exitPresenter\(\)/)
  assert.match(bridge, /Presenter Fullscreen/)
  assert.match(bridge, /button\[title="Play Mode"\]/)
  assert.match(drawings, /MAX_DRAWING_BYTES/)
  assert.match(drawings, /ALLOWED_ELEMENTS/)
  assert.match(drawings, /javascript:/)
  assert.doesNotMatch(drawings, /v-html/)
})
